Feature/gallery
KitsuneAkvma/tankteam-project-1 pull request #13
Opened 2022-09-02 16:05 UTC by DamianSikorski

Dodałem zdjęcia z usuniętym tłem aby ustawić ja linear-gradietem. <picure>, które jest zakomentowałe, nie wyświetlało mi żadnych obrazków ( w inspektorze pojawiała się jakaś dziwna scieżka różniąca się od tej co w vscode ) Sprawę udało się załatawić za pomocą <img> zdjęcia łądnie się zmieniają w zależności od szerokości ekranu i gęstości pikseli.  Sekcja wydaje się być skończona.  Jakieś sugestie dlaczego <picture> nie zadziałało?

2022-09-02 20:30 UTC, MalgorzataMarczynska requested changes

2022-09-02 20:30 UTC, MalgorzataMarczynska commented on src/partials/gallery.html
> +    (max-width:   767px) 320px,
wielokrotna spacja - nie wiem, czy ma to jakiekolwiek znaczenie, ale czasem cuda się dziejąm więc można poprawić

2022-09-02 20:30 UTC, MalgorzataMarczynska commented on src/partials/gallery.html
> +    (min-width: 768px) and (max-width: 1199px) 768px,
max-width tu chyba powinien być 1279px, jak w linii poniżej, bo teraz nasz punkt przegięcia to 1280px?

2022-09-02 20:30 UTC, MalgorzataMarczynska commented on src/partials/gallery.html
> -<section class="gallery">gallery</section>
dodaj od razu id dla doroty, żeby można było podpiąć kotwice

2022-09-02 20:30 UTC, MalgorzataMarczynska commented on src/sass/_gallery.scss
> +  height: 122px;
height może lepiej na auto? ale to oczywiście tylko sugestia, może dobrze się skaluje, wiec tylko do ponownego rzucenia okiem

2022-09-02 20:30 UTC, MalgorzataMarczynska commented on src/sass/_gallery.scss
> +@media screen and (min-width: 1200px) {
punkt przegięcia 1280px

2022-09-02 20:30 UTC, MalgorzataMarczynska commented on src/sass/_gallery.scss
> +@media screen and (min-width: 768px) {
dwa razy powtórzone to samo medium

2022-09-03 09:49 UTC, MalgorzataMarczynska approved these changes

2022-09-03 18:14 UTC, KitsuneAkvma approved these changes
Poprawnie, id zostało dodane

2022-09-04 16:06 UTC, merged