Feature/kamil.modal buy
KitsuneAkvma/tankteam-project-1 pull request #63
Opened 2022-09-06 15:14 UTC by KamilSzafranski

2022-09-06 16:08 UTC, kwiatkowsko requested changes
Omówione na czacie poprawki.

2022-09-06 18:48 UTC, KamilSzafranski commented
> Omówione na czacie poprawki.

Poprawione

2022-09-06 21:55 UTC, KitsuneAkvma requested changes
- Przydałby się jakiś kontener żeby to nie było tak blisko granicy

![obraz](https://user-images.githubusercontent.com/106407746/188745881-121f5e0c-57e1-4b18-a6f7-b1b12c15c8af.png)

- Chose na choose :) 
![obraz](https://user-images.githubusercontent.com/106407746/188746079-c9313194-4f2d-42b4-9a8f-f40da3f824ca.png)

- Usnunąć upper case - średnio pasuje do czcionki i fontu 
![obraz](https://user-images.githubusercontent.com/106407746/188747041-8ff718be-6d5a-4bed-b6ad-88f45488feb2.png)

- Zwiększyć gapy pomiędzy labelami i zwiększyć trochę kontrast pól bo się to troszkę zlewa 
![obraz](https://user-images.githubusercontent.com/106407746/188747196-caaddf6d-32b4-498b-ba1d-b8ec85264f65.png)

- Select effect też do poprawki bo się nie wyróżnia za bardzo ( może inner shadow)
![obraz](https://user-images.githubusercontent.com/106407746/188747271-90dbafa7-d338-4cae-9e52-53d8596fd2c4.png)

- Button powinien mieć 2rem radius
![obraz](https://user-images.githubusercontent.com/106407746/188747578-2dc20b01-2a1a-4d04-b84b-83c2ab02699b.png)

- Button w mobile-menu nie działa 
![obraz](https://user-images.githubusercontent.com/106407746/188747665-9bda7e17-51f4-4155-ab05-3f87bee2ad14.png)


Ogólnie to dobra robota Kamil. Fajnie to wygląda, podziwiam za chęci.🔥🔥🔥🔥

2022-09-07 20:34 UTC, kwiatkowsko commented
Świetna robota!
Przepraszam, że dopiero teraz sprawdzam, ostatnia kosmetyka:
- country zgubiło literkę r - chyba, że chodziło Ci o wpisanie hrabstwa :p
-  &:focus-within {
      box-shadow: getColor(accent) 0px 2px 5px -1px, getColor(accent) 0px 1px 3px -1px;
    } albo zmień promień z 5px na 2px albo kolor na secondary-pink - ale to już kosmetyka
- możnaby odsunąć tego X troszeczkę, ale to też kosmetyka
- musisz mi zrobić rebase, bo zaszło za dużo zmian, a sama tego nie zrobię, bo nie wiem co w Twoim kodzie powinno zostać :p

Stopka świetna, dokładnie tak miała wyglądać :)

2022-09-07 21:42 UTC, KamilSzafranski commented
> Świetna robota! Przepraszam, że dopiero teraz sprawdzam, ostatnia kosmetyka:
> 
> * country zgubiło literkę r - chyba, że chodziło Ci o wpisanie hrabstwa :p
> * &:focus-within {
>   box-shadow: getColor(accent) 0px 2px 5px -1px, getColor(accent) 0px 1px 3px -1px;
>   } albo zmień promień z 5px na 2px albo kolor na secondary-pink - ale to już kosmetyka
> * możnaby odsunąć tego X troszeczkę, ale to też kosmetyka
> * musisz mi zrobić rebase, bo zaszło za dużo zmian, a sama tego nie zrobię, bo nie wiem co w Twoim kodzie powinno zostać :p
> 
> Stopka świetna, dokładnie tak miała wyglądać :)

zrobione

2022-09-07 21:49 UTC, kwiatkowsko approved these changes
cudownie, puszczam

2022-09-07 21:50 UTC, merged