Feature/agnieszka/products desktop
KitsuneAkvma/tankteam-project-1 pull request #64
Opened 2022-09-06 16:38 UTC by AgnieszkaBaranowska

wersja na desktop+ dodanie hovera, 
Te 3 kropki w kartach produktów zrobiłam w html zamiast pseudoelement

2022-09-06 18:04 UTC, kwiatkowsko requested changes
Dodaj proszę na widoku tabletu większy odstęp do dołu od buttona.

2022-09-06 18:42 UTC, AgnieszkaBaranowska commented
poprawione :)

2022-09-06 22:24 UTC, kwiatkowsko commented
Ostatnie poprawki! Obiecuję! 

- [ ] transform: scale(1.02); - dla komórki 

- [ ] transform: scale(1.03); - dla tabletu

- [ ] wyrzucenie hovera z buttona
Ślicznie będzie!

2022-09-07 20:38 UTC, kwiatkowsko requested changes
![image](https://user-images.githubusercontent.com/96976740/188972693-afb39aa9-847e-453d-94af-5fc4d593e8b2.png)
ostatnia zmiana - kropki się zrobiły podwójne
rebase i pójdzie :)
Świetna robota!

2022-09-07 20:47 UTC, kwiatkowsko commented
+ czy można usunąć te 200 linii zakomentowanego kodu? :D

2022-09-08 16:22 UTC, closed without merging

2022-09-08 16:23 UTC, kwiatkowsko commented
zmiany dodane w innym branchu